Repository omise/omise-woocommerce, pull requests merged in 2019-01, with the labels that each got.

#91 Removing the deprecated function (from jQuery's reported)
  assets/javascripts/omise-payment-form-handler.js
Labels: Status: Ready

#95 Refactoring plugin-initial code structure - part 2: Relocating, renaming functions and method.
  includes/gateway/class-omise-payment-creditcard.php
  omise-woocommerce.php
Labels: Status: Review needed, Type: Enhancement

#96 Refactoring plugin-initial code structure - part 3: Organizing Omise_Admin class
  includes/class-omise-admin.php
  omise-woocommerce.php
Labels: Status: Ready, Type: Enhancement

#93 Upgrade Omise-PHP library from v2.8.0 to v2.11.1.
  includes/libraries/omise-php/CHANGELOG.md
  includes/libraries/omise-php/README.md
  includes/libraries/omise-php/lib/Omise.php
  includes/libraries/omise-php/lib/omise/OmiseAccount.php
  includes/libraries/omise-php/lib/omise/OmiseBalance.php
  includes/libraries/omise-php/lib/omise/OmiseCapabilities.php
  includes/libraries/omise-php/lib/omise/OmiseCard.php
  includes/libraries/omise-php/lib/omise/OmiseCardList.php
  includes/libraries/omise-php/lib/omise/OmiseCharge.php
  includes/libraries/omise-php/lib/omise/OmiseCustomer.php
  includes/libraries/omise-php/lib/omise/OmiseDispute.php
  includes/libraries/omise-php/lib/omise/OmiseEvent.php
  includes/libraries/omise-php/lib/omise/OmiseForex.php
  includes/libraries/omise-php/lib/omise/OmiseLink.php
  includes/libraries/omise-php/lib/omise/OmiseOccurrence.php
  includes/libraries/omise-php/lib/omise/OmiseOccurrenceList.php
  includes/libraries/omise-php/lib/omise/OmiseRecipient.php
  includes/libraries/omise-php/lib/omise/OmiseRefund.php
  includes/libraries/omise-php/lib/omise/OmiseRefundList.php
  includes/libraries/omise-php/lib/omise/OmiseSchedule.php
  includes/libraries/omise-php/lib/omise/OmiseScheduleList.php
  includes/libraries/omise-php/lib/omise/OmiseScheduler.php
  includes/libraries/omise-php/lib/omise/OmiseSearch.php
  includes/libraries/omise-php/lib/omise/OmiseSource.php
  includes/libraries/omise-php/lib/omise/OmiseTest.php
  includes/libraries/omise-php/lib/omise/OmiseTransaction.php
  includes/libraries/omise-php/lib/omise/OmiseTransfer.php
  includes/libraries/omise-php/lib/omise/res/OmiseApiResource.php
  includes/libraries/omise-php/lib/omise/res/OmiseVaultResource.php
Labels: Status: Ready, Type: Enhancement

#98 Added filter hooks for charge.description and charge.metadata
  includes/gateway/class-omise-payment-alipay.php
  includes/gateway/class-omise-payment-creditcard.php
  includes/gateway/class-omise-payment-internetbanking.php
Labels: Status: Ready, Type: Feature request
