Repository omise/omise-woocommerce, pull requests merged in 2020-09, with the labels that each got.

#188 Adding permission to callback which helps to removes a warning message on Wordpress 5.5.
  includes/class-omise-rest-webhooks-controller.php
Labels: Status: Review needed, Type: Bug

#189 Updating deprecated functions in WooCommerce v3
  includes/class-omise-callback.php
  includes/gateway/abstract-omise-payment-offline.php
  includes/gateway/class-omise-payment-alipay.php
  includes/gateway/class-omise-payment-creditcard.php
  includes/gateway/class-omise-payment-installment.php
  includes/gateway/class-omise-payment-internetbanking.php
  includes/gateway/class-omise-payment-truemoney.php
  includes/gateway/class-omise-payment.php
Labels: Status: Review needed

#190 ✨ Releasing Omise-WooCommerce v4.2
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Status: Review needed

#149 Introducing Konbini payment method
  assets/css/omise-css.css
  includes/class-omise-localization.php
  includes/class-omise-payment-factory.php
  includes/gateway/class-omise-payment-konbini.php
  omise-woocommerce.php
  templates/payment/form-konbini.php
Labels: Status: Review needed, Type: Feature, Type: Feature request

#185 PayNow, adding a link to the QR code url at the order-confirmation email
  includes/gateway/class-omise-payment-paynow.php
Labels: Status: In progress, Type: Enhancement, Type: Feature request
