Repository omise/omise-woocommerce, pull requests merged in 2022-06, with the labels that each got.

#275 [APM2-695] FPX logo, banklist and terms & condition
  assets/css/omise-css.css
  assets/images/fpx-bocm.svg
  assets/images/fpx.svg
  includes/classes/class-omise-image.php
  includes/gateway/class-omise-payment-fpx.php
  includes/gateway/class-omise-payment-ocbc-pao.php
  templates/payment/form-fpx.php
Labels: Type: Enhancement

#277 Release 4.20.1
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Type: Release

#278 [EM-1997] Added Google Pay payment method
  .gitignore
  assets/css/omise-css.css
  assets/javascripts/googlepay-button-index.umd.min.js
  assets/javascripts/omise-payment-form-handler.js
  includes/class-omise-payment-factory.php
  includes/classes/class-omise-image.php
  includes/gateway/abstract-omise-payment-base-card.php
  includes/gateway/class-omise-payment-creditcard.php
  includes/gateway/class-omise-payment-googlepay.php
  includes/gateway/class-omise-payment.php
  omise-woocommerce.php
  templates/payment/form-googlepay.php
Labels: Status: Ready

#279 Release v4.21
  CHANGELOG.md
  includes/gateway/abstract-omise-payment-base-card.php
  omise-woocommerce.php
  readme.txt
Labels: Type: Release

#280 [EM-1997] Fix Googlepay for live mode
  CHANGELOG.md
  includes/gateway/class-omise-payment-googlepay.php
  omise-woocommerce.php
  readme.txt
Labels: Progress: In review
