Repository omise/omise-woocommerce, pull requests merged in 2022-04, with the labels that each got.

#255 Add Release Workflow
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: Type: Enhancement

#257 [APM2-625] update assets for mobile banking logo
  assets/css/omise-css.css
  assets/images/bbl-m.png
  assets/images/kma.png
  assets/images/scb-easy.png
  includes/backends/class-omise-backend-mobile-banking.php
Labels: Type: Enhancement

#258 v4.19.0 release
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Type: Release

#259 Set release workflow depends on tag versioning
  .github/workflows/release.yml
Labels: Type: Enhancement

#262 [APM2-620] Fix OCBC Pay Anyone cannot back to the order success page.
  assets/css/omise-css.css
  includes/backends/class-omise-backend-mobile-banking.php
  includes/class-omise-rest-webhooks-controller.php
  includes/gateway/class-omise-payment-mobilebanking.php
Labels: Type: Bug

#263 Release 4.19.2
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Type: Release
