Repository omise/omise-woocommerce, pull requests merged in 2022-05, with the labels that each got.

#269 Release 4.19.3
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Type: Release

#270 [EM-1800] Add GrabPay payment method
  includes/class-omise-payment-factory.php
  includes/gateway/class-omise-payment-grabpay.php
  omise-woocommerce.php
Labels: Type: Enhancement, Status: Ready

#273 Enhance Release Workflow
  .github/workflows/release.yml
Labels: Type: Enhancement
