Repository omise/omise-woocommerce, pull requests merged in 2022-03, with the labels that each got.

#246 [APM2-213] [APM2-504] Add support for moblie banking KBank and SCB
  assets/css/omise-css.css
  assets/images/kplus.png
  includes/backends/class-omise-backend-mobile-banking.php
  includes/gateway/class-omise-payment-mobilebanking.php
Labels: Type: Enhancement

#250 Remove mobile banking OCBC PAO
  assets/css/omise-css.css
  includes/backends/class-omise-backend-mobile-banking.php
  includes/gateway/class-omise-payment-mobilebanking.php
Labels: Type: Bug

#249 [APM2-579] Add checkout filter currency for mobile banking
  assets/css/omise-css.css
  includes/backends/class-omise-backend-mobile-banking.php
  includes/class-omise-capabilities.php
  includes/gateway/class-omise-payment-mobilebanking.php
Labels: Type: Bug

#248 [EM-1690] Add Rabbit LINE Pay payment method
  includes/class-omise-admin.php
  includes/class-omise-callback.php
  includes/class-omise-payment-factory.php
  includes/events/class-omise-event-charge-capture.php
  includes/events/class-omise-event-charge-complete.php
  includes/gateway/class-omise-payment-creditcard.php
  includes/gateway/class-omise-payment-rabbit-linepay.php
  includes/gateway/class-omise-payment.php
  omise-woocommerce.php
Labels: Type: Bug, Type: Feature, Progress: In review

#247 Release 4.17
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Type: Release

#251 Release 4.17.1
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Type: Release

#252 [APM2-561] [APM2-551] Add support for moblie banking BAY and BBL
  assets/css/omise-css.css
  includes/backends/class-omise-backend-mobile-banking.php
Labels: Type: Enhancement

#254 Release 4.18
  CHANGELOG.md
  omise-woocommerce.php
  readme.txt
Labels: Type: Release
